project:
  type: website
  output-dir: docs

website:
  title: "Python Wokrshop"
  bread-crumbs: false
  navbar:
    left:
      - text: Python Basic
        menu:
          - href: 1_environment.qmd
            text: (1) Python 개발 환경
          - href: 2_basic.qmd
            text: (2) 기초 문법
          - href: 3_structure.qmd
            text: (3) 자료구조
          - href: 4_string.qmd
            text: (4) 문자열
      - text: Data Wrangling
        menu:
          - href: 5_numpy.qmd
            text: (1) NumPy
          - href: 6_pandas.qmd
            text: (2) Pandas
      - text: Analysis
        menu:
          - href: 7_EDA.qmd
            text: (1) 기술통계
          - href: 8_analysis.qmd
            text: (2) 가설 검정
      - text: Visualization
        menu:
          - href: 9_matplotlib.qmd
            text: (1) Matplotlib
          - href: 10_seaborn.qmd
            text: (2) Seaborn
      
format:
  html:
    theme:
      - simplex
    css: styles.css
    toc: true
    toc-location: right
    toc-expand: true

